# Example Lavalink application.yml configuration with ICY Stream Plugin
# Version: 1.1.0 with improved error handling for ResponseHeaderFilter issues

server:
  port: 2333
  address: 0.0.0.0
  
  # Undertow configuration to handle ICY streams better
  undertow:
    # Increase buffer sizes for ICY streams
    buffer-size: 16384
    io-threads: 4
    worker-threads: 64
    direct-buffers: true
    
    # Increase max headers size for ICY metadata
    max-http-header-size: 8192

lavalink:
  plugins:
    - dependency: "com.github.ZenKho-chill:zk.icy.stream.lavalink:v1.1.0"
      repository: "https://jitpack.io"
  
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true          # Required for ICY streams
      local: false
    
    # Increased buffers for better streaming performance
    bufferDurationMs: 1000
    frameBufferDurationMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  icy:
    # Enable automatic reconnection when stream connection is lost
    autoReconnect: true
    
    # Enable metadata extraction from ICY streams (song titles, artist info)
    # Set to false if experiencing header parsing issues
    enableMetadata: true
    
    # Increased timeouts for better reliability
    connectionTimeout: 20000  # 20 seconds
    readTimeout: 45000       # 45 seconds
    
    # Maximum number of reconnection attempts
    maxRetries: 5
    
    # Delay between reconnection attempts in milliseconds
    retryDelay: 3000         # 3 seconds
    
    # Follow HTTP redirects (301, 302, etc.)
    followRedirects: true

logging:
  level:
    root: INFO
    lavalink: INFO
    com.zenkho.icy: DEBUG
    
    # Enable these for debugging ResponseHeaderFilter issues
    # lavalink.server.io: DEBUG
    # io.undertow: DEBUG
